### ISSUE TITLE
Looks like you need to unlock your wallet

### ISSUE THREAD

**Issue by MikooDev** [gladiusio/gladius-node-client#7]
I have a wallet on myetherwallet and when i put in its adress and click 'Request to join pool' a popup appears and says that i need to unlock my wallet. How can i do that?

**Comment by jkolarov** [comment]
+1 same problem. I tried 2 different wallets, none of which is myetherwalled.

**Comment by kleoken** [comment]
You need to have MetaMask installed

**Comment by jkolarov** [comment]
I tried this, but nothing happens. Some details bellow:

![Imgur](https://i.imgur.com/hnU9HUx.png?1)

And the error 

`bluebird.js:1468 
Unhandled rejection Error: ERROR: The returned value is not a convertible string:
    at SolidityTypeString.formatOutputString [as _outputFormatter] (http://localhost:3000/static/js/bundle.js:110546:15)
    at http://localhost:3000/static/js/bundle.js:111426:25
    at SolidityTypeString../node_modules/web3-eth-abi/src/type.js.SolidityType.decode (http://localhost:3000/static/js/bundle.js:111427:11)
    at http://localhost:3000/static/js/bundle.js:110924:49
    at Array.forEach (<anonymous>)
    at ABICoder../node_modules/web3-eth-abi/src/index.js.ABICoder.decodeParameters (http://localhost:3000/static/js/bundle.js:110923:13)
    at Contract../node_modules/web3-eth-contract/src/index.js.Contract._decodeMethodReturn (http://localhost:3000/static/js/bundle.js:119186:22)
    at Method.outputFormatter (http://localhost:3000/static/js/bundle.js:119538:46)
    at Method../node_modules/web3-core-method/src/index.js.Method.formatOutput (http://localhost:3000/static/js/bundle.js:99234:54)
    at sendTxCallback (http://localhost:3000/static/js/bundle.js:99525:33)
From previous event:
    at PromiEvent (http://localhost:3000/static/js/bundle.js:105404:24)
    at send (http://localhost:3000/static/js/bundle.js:99518:21)
    at Object._executeMethod (http://localhost:3000/static/js/bundle.js:119546:24)
    at Object.callback (http://localhost:3000/static/js/bundle.js:128094:74)
    at sendTxCallback (http://localhost:3000/static/js/bundle.js:99536:29)
    at http://localhost:3000/static/js/bundle.js:105785:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4120:13
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1336:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1333:13
    at end (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9953:11)
printWarning @ bluebird.js:1468
formatAndLogError @ bluebird.js:1184
fireRejectionEvent @ bluebird.js:1209
Promise._notifyUnhandledRejection @ bluebird.js:715
(anonymous) @ bluebird.js:141
setTimeout (async)
(anonymous) @ bluebird.js:140
(anonymous) @ bluebird.js:4330
attributes (async)
(anonymous) @ bluebird.js:4316
attributes (async)
scheduleToggle @ bluebird.js:4324
schedule @ bluebird.js:4333
Async.invokeLater @ bluebird.js:139
Promise._ensurePossibleRejectionHandled @ bluebird.js:695
Promise._reject @ bluebird.js:3246
Promise._settlePromise @ bluebird.js:3168
Promise._settlePromise0 @ bluebird.js:3198
Promise._settlePromises @ bluebird.js:3277
(anonymous) @ bluebird.js:162
(anonymous) @ bluebird.js:4330
attributes (async)
(anonymous) @ bluebird.js:4316
attributes (async)
scheduleToggle @ bluebird.js:4324
schedule @ bluebird.js:4333
Async.settlePromises @ bluebird.js:161
Promise._reject @ bluebird.js:3243
Promise._rejectCallback @ bluebird.js:3058
(anonymous) @ bluebird.js:3069
(anonymous) @ index.js:76
setTimeout (async)
_fireError @ index.js:75
sendTxCallback @ index.js:471
(anonymous) @ index.js:144
(anonymous) @ inpage.js:9909
completeRequest @ inpage.js:9960
(anonymous) @ inpage.js:683
replenish @ inpage.js:1203
iterateeCallback @ inpage.js:1193
(anonymous) @ inpage.js:1168
(anonymous) @ inpage.js:9837
(anonymous) @ inpage.js:9933
(anonymous) @ inpage.js:3345
replenish @ inpage.js:1208
(anonymous) @ inpage.js:1212
eachLimit$1 @ inpage.js:3431
(anonymous) @ inpage.js:1242
runReturnHandlers @ inpage.js:9932
(anonymous) @ inpage.js:4115
replenish @ inpage.js:1208
iterateeCallback @ inpage.js:1193
(anonymous) @ inpage.js:1168
(anonymous) @ inpage.js:4120
(anonymous) @ inpage.js:1336
(anonymous) @ inpage.js:683
replenish @ inpage.js:1203
iterateeCallback @ inpage.js:1193
(anonymous) @ inpage.js:1168
(anonymous) @ inpage.js:1333
end @ inpage.js:9953
setTimeout (async)
write @ inpage.js:10105
doWrite @ inpage.js:12768
writeOrBuffer @ inpage.js:12757
Writable.write @ inpage.js:12684
ondata @ inpage.js:11749
EventEmitter.emit @ inpage.js:9442
addChunk @ inpage.js:11421
readableAddChunk @ inpage.js:11408
Readable.push @ inpage.js:11375
_write @ inpage.js:10425
doWrite @ inpage.js:12768
writeOrBuffer @ inpage.js:12757
Writable.write @ inpage.js:12684
ondata @ inpage.js:11749
EventEmitter.emit @ inpage.js:9442
addChunk @ inpage.js:11421
readableAddChunk @ inpage.js:11408
Readable.push @ inpage.js:11375
PostMessageStream._onMessage @ inpage.js:10808
postMessage (async)
PostMessageStream._write @ contentscript.js:3463
doWrite @ contentscript.js:5405
writeOrBuffer @ contentscript.js:5394
Writable.write @ contentscript.js:5321
ondata @ contentscript.js:4386
EventEmitter.emit @ contentscript.js:2501
addChunk @ contentscript.js:4058
readableAddChunk @ contentscript.js:4045
Readable.push @ contentscript.js:4012
PortDuplexStream._onMessage @ contentscript.js:161
EventImpl.dispatchToListener @ VM63 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM69 extensions::utils:138
EventImpl.dispatch_ @ VM63 extensions::event_bindings:387
EventImpl.dispatch @ VM63 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM69 extensions::utils:138
dispatchOnMessage @ VM70 extensions::messaging:392`

**Comment by ditrone** [comment]
@jkolarov 

I found the solution! You need to click on the browser extension MetaMask you installed in chrome, accept their terms and conditions, then you can create a password for that extension. It is in that extension you perform the unlock, not the ether wallet! Error message could be more informative :)

**Comment by MikooDev** [comment]
Where exactly i can unlock it. I searched through entire metamask and only found 'Lock'

**Comment by ditrone** [comment]
@MikooDev I've put a step by step guide here:

http://devbeforenull.com/index.php/2017/12/30/gladius-looks-like-you-need-to-unlock-your-wallet/

**Comment by MikooDev** [comment]
After i did those steps I didn't get this popup, but i got this error 
`./src/components/GetIP.js
  Line 47:  Do not mutate state directly. Use setState()  react/no-direct-mutation-state
printWarnings @ webpackHotDevClient.js:136
webpackHotDevClient.js:136 ./src/components/JoinPool.js
  Line 29:  Unnecessary escape character: \[              no-useless-escape
  Line 29:  Unnecessary escape character: \[              no-useless-escape
  Line 80:  Do not mutate state directly. Use setState()  react/no-direct-mutation-state
printWarnings @ webpackHotDevClient.js:136
bluebird.js:1468 Unhandled rejection Error: ERROR: The returned value is not a convertible string:
    at SolidityTypeString.formatOutputString [as _outputFormatter] (http://localhost:3000/static/js/bundle.js:110546:15)
    at http://localhost:3000/static/js/bundle.js:111426:25
    at SolidityTypeString../node_modules/web3-eth-abi/src/type.js.SolidityType.decode (http://localhost:3000/static/js/bundle.js:111427:11)
    at http://localhost:3000/static/js/bundle.js:110924:49
    at Array.forEach (<anonymous>)
    at ABICoder../node_modules/web3-eth-abi/src/index.js.ABICoder.decodeParameters (http://localhost:3000/static/js/bundle.js:110923:13)
    at Contract../node_modules/web3-eth-contract/src/index.js.Contract._decodeMethodReturn (http://localhost:3000/static/js/bundle.js:119186:22)
    at Method.outputFormatter (http://localhost:3000/static/js/bundle.js:119538:46)
    at Method../node_modules/web3-core-method/src/index.js.Method.formatOutput (http://localhost:3000/static/js/bundle.js:99234:54)
    at sendTxCallback (http://localhost:3000/static/js/bundle.js:99525:33)
From previous event:
    at PromiEvent (http://localhost:3000/static/js/bundle.js:105404:24)
    at send (http://localhost:3000/static/js/bundle.js:99518:21)
    at Object._executeMethod (http://localhost:3000/static/js/bundle.js:119546:24)
    at Object.callback (http://localhost:3000/static/js/bundle.js:128094:74)
    at sendTxCallback (http://localhost:3000/static/js/bundle.js:99536:29)
    at http://localhost:3000/static/js/bundle.js:105785:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4120:13
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1336:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1333:13
    at end (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9953:11)
printWarning @ bluebird.js:1468`

**Comment by MikooDev** [comment]
BTW you have discord or sth. It'd be way easier for me to talk to you (im Mikoo#9139)
