### ISSUE TITLE
Unhandled rejection Error - bluebird.js

### ISSUE THREAD

**Issue by AssessOne** [gladiusio/gladius-node-client#8]
Hi All,

I have been able to install the Gladius node interface and metamask etc, however I cannot get past the following screen:

![image](https://user-images.githubusercontent.com/8427365/34596095-314d29e6-f231-11e7-93ef-a3d27447c8f0.png)

The following error is reported in bluebird.js when clicking on "Request to join pool":

```
Unhandled rejection Error: ERROR: The returned value is not a convertible string:
    at SolidityTypeString.formatOutputString [as _outputFormatter] (http://175.137.31.2:3000/static/js/bundle.js:110546:15)
    at http://175.137.31.2:3000/static/js/bundle.js:111426:25
    at SolidityTypeString../node_modules/web3-eth-abi/src/type.js.SolidityType.decode (http://175.137.31.2:3000/static/js/bundle.js:111427:11)
    at http://175.137.31.2:3000/static/js/bundle.js:110924:49
    at Array.forEach (<anonymous>)
    at ABICoder../node_modules/web3-eth-abi/src/index.js.ABICoder.decodeParameters (http://175.137.31.2:3000/static/js/bundle.js:110923:13)
    at Contract../node_modules/web3-eth-contract/src/index.js.Contract._decodeMethodReturn (http://175.137.31.2:3000/static/js/bundle.js:119186:22)
    at Method.outputFormatter (http://175.137.31.2:3000/static/js/bundle.js:119538:46)
    at Method../node_modules/web3-core-method/src/index.js.Method.formatOutput (http://175.137.31.2:3000/static/js/bundle.js:99234:54)
    at sendTxCallback (http://175.137.31.2:3000/static/js/bundle.js:99525:33)
From previous event:
    at PromiEvent (http://175.137.31.2:3000/static/js/bundle.js:105404:24)
    at send (http://175.137.31.2:3000/static/js/bundle.js:99518:21)
    at Object._executeMethod (http://175.137.31.2:3000/static/js/bundle.js:119546:24)
    at Object.callback (http://175.137.31.2:3000/static/js/bundle.js:128094:74)
    at sendTxCallback (http://175.137.31.2:3000/static/js/bundle.js:99536:29)
    at http://175.137.31.2:3000/static/js/bundle.js:105785:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4120:13
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1336:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1333:13
    at end (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9953:11)
```
This error occurs both in Firefox and Chrome with metamask plugin installed.

Any suggestions on how this can be resolved please?

Thank you

James

**Comment by sebastianhutter** [comment]
I see the same error messages - I assume that this has to do with the missing pool information - i assume the script gets a NULL value back and is not able to work with that.

**Comment by MikooDev** [comment]
i have the same problem
